group: bluezone
dist: trusty
sudo: false
language: node_js
node_js:
- 6.9.0
addons:
  sonarqube: true
install:
- npm i -g npm@3
- npm install
script:
- npm test
- sonar-scanner -D sonar.host.url=$SONAR_HOST_URL -D sonar.github.endpoint=$GH_API_URL
  -D sonar.github.oauth=$SONAR_GITHUB_TOKEN
after_success:
- npm run build
- npm run semantic-release
cache:
  directories:
  - node_modules
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
env:
  global:
  - SONAR_HOST_URL=http://ux-dev-sonar.rtp.raleigh.ibm.com:9000/
  - GH_API_URL=https://github.ibm.com/api/v3
  - secure: ZX1PdAMZYHknu+D7BwCa5KsLe+oPE/JCFaNSGO97i5L7REchunBVPaO2K1fiilvfxGgSaUuwMIWd3x2dgha22kSKRfdda+csvLJgv66Vj0WCXd27l1PJuJVBv3ByGmi1/z9TA7pwShtm15AB8UOC2VwOTpyY+E8HRsnnj0rSSXtLj/EoZYpeYZvvw+GMbBU7aZtTGqCrYq7n4ZBBEFUWpqzGlJkpJ+QrLTTdR/cUvojKnPG6L/6lezBQRSL7b/RtbmoSOtNoP54HnHZJ2gi6kvcX19TNNEFGw1ytG4BbZRa4wIB1RchSAdq8WB9PQI7WenoahruAzn/DGS0T2cC457+swEZ3baKMh/NG9N1lBbzHZrIo1zF+W46c4kXzUiQ6qtmk6Sv4BY2NkOzF2YkdWmtb1fG9Vak7/Tbe6Z30VfSmlcBm7s9m5DgBtT7rk7MSZIIuQOVoh+g9UoGeUdptC9zjFw4KSU24yy4JK19RF06257MPbdDB9IO0tfDn5A8F6wlFe7pBOpCNLjTGqK9+FDSoQxGioNKGYgvllHPsCz80EdbZTVdhyiLmHUbgFBe4JW/shiZ6qu46le6MzOzCEAZ9e2MKPswkCl/LUillozNNB1vj6hirbQp0ZZj8TOgEmtVfthmL7U2AuZOXILABZJF5PTrfGkM9iquOElR7Yyw=
  - secure: AYAEPS203NkSjNjNy5Qv6bi0fv+0v+vrZ6zRR+gBa7fPWxnZ9orsusVbUqdCewtWPFagDAYERLgo1tEaE3BzQFhGDJ6fqFw9RwyPCSH29BP0fQk/FsIuhJYh3oPGzW7wra8JDYoMS05ICGziGTdUDgvEUQy7ACRh/AXbOUVTsbYfokol4Hs4YH9PGuTNnnPUpkG9sziMTqcho31dhjuNC/ppPqS3SCR+V102du7O97eeWZ87Xgg4pzlofPWuODzWxuiRCBZzK0VKX7o4H6w67gc0vDNWTDOTSo3bhKZXxH+2020idy428sDm9TbCOygmx78OqR132W0oKV9EXtmRSEzurQV+zgK0IVdAQqz5o584n59bXXyS4hBNZf5EaTml25udYrOWwrtu+1TtxwbpG8SVbsO6anRfUF45PStrAIjI84S0+Hrdjqogr5Aj8VWGo7bjZNzwcp53di5x4txuoeDuaokv/TSAEgrXWUemS/Fym1zyXva6PlR/mtMekt75AzWphO2GCWwpiJJv1ZdUv4dry7/rFiqN+0SaMepHGuY7AnQM41GrtCxD51p+HBzCNsSdx5YzowG7klHtD3ny07wBfEXXSk75bQLGIoiLPSTZK8v/OtXx5n9bB9XRXPVOqonhp5jQvpg3PlWRpQgThXBy2GgBHDavkNqu+qhlsSY=
  - secure: mkkLAEzLH6htCePrkbYfbKOrZcitF4A1D6lxjbz6quxrDkPQSXpLeF3QWKAJ1skmJoTAT4i6Qy5lVUD2WPOTgkTM9OHGplyAzBIqYk3aNoyDQcFMtv0skoTvSthloJYjuGhYKL2t8avok7pAtvR4aUejTSSHt+6HktxVzaIXULE/7nX975kNdauvMvY0JxptJZ7rMdTlktT8LPyUh0Vpw8NDZ3clOd3QeYWYxQX3oaTUD6BRM8pQmflilwlYY8n4CCbOaoGTRutuQcxyP4Rs84pdR8ZPPcI/TJLQVC7rr1944lluW0DqkryCXrdIlW7tGzXv5bgtN7hOT9hezRMMB23/tItoAScC6w4NcTJd0jx/07/FB+iuEq7c5bDhI5iwzceZYYt/jDIfu2/VadA2Z0xzfBUrU37eq7fvZYtP4UUu7io+mAQzdoxn59azeN20SoUx31/3AGu7s1SrqbC0VXM6Fgf61l4YrwozoiLpy6ta7S9Xo3i72s5Ahktl7VrXTJuj4wKSTCM7tepUbAwurnhZf0+TyQQzFhWDNcDN6oZCSNjo/waegRb76caHEBLfxPaY5BjfRbk8ENfQxq0q893p7hWqnBwkZB6qkSzC56Ud72WibDxqBFfPk2ucQtssA04ZYupNokva2YRQ0vw6jGce0uQGdZMOK6+338AcAEw=
  - secure: Ny5CuwC1AzYUjLs49YTh/LAAbCmDp/jfZMiSkxCpt9PZnPqAYK2I6ZAXJO+0/iiKiYvvvfmngXzl9qBex9ZNJGYT6/tXWTJl22YwPSdnCUwhQPcU1axq5XLv9+phsKVUEY+XK9llR1GCygQZ0zV3pb8j+GQ8G/wZq77hDA1ziXq4ogbcGWngOKYJ97XVnxHxDhKwJmEqK3eV8lKk3Tvxac72dhyVcxFkRN+wOXw4VLEw4Zt1hB5TUHGZWv22yaZlL5TSi3ybO7ShrdAs+ByvAGV1N/0zXiN8Q137Ek2Awzhqv2P878rm41r0r1dwYQrjhhN1QcKP95xyP3/20HZAGTTQF5Z5slzUngtXtROqidQnunm0yAsfxw/2TdCbzjlMh0dIZqqvEgHm8uoVYnw9PpHu6gWHWsu/Ig0tLmeSuzlb09p/j2Wng9zg65Qkbqc+rDiLt7wWXD3PlipMOp1xVgc8zNM9gwRCmN/HYyI8IKtIr8+ivmAJF3b26x8mbVvVgrOOSt4/DFz7YcJ6xGoyibRFIiuIs20w5M8PZeIlUZ0DRoZ4QBAI6na1Hjo1px75NVavIRnhZdFKNG8/FGgKrij8stf8kp91xersIsXeKZlk7I+9OljV2mPFI+WxsjEXwaF/ElTylgOQkXRLOZvesIKP4RqIcQy+B7FOpI3WXww=
notifications:
  slack:
    rooms:
      secure: uPtI+syOyuJuzX+k7agHoWnVu32M3hHyrXjO8oZX71TgRbPOpDcGUOJvGmwrtumoRv63qPmXFnlF8657fFn/8fjF6DOe99X9KVmhSy+JELUy953pOM70yLcHVxVNRytrHKG2UJQCq0BCaNb4xoCG4hU/OdCanEK2zJRM0rXNKqnibyAGFiSL87qYA0EgKSeQX/FdzAHz2E+rBw9EYNCyYEzcQPMkL7wGS2+Y7+yzZfSgU7AtFqsHmDWaqWeUwvCLIMtpYncrqIf3YDKgYT5Z4IDe431rLUvf46RTVUcPdJvXnp0hawktxkA405SIfp3TcxKgLAV1yGUzJDfiVVjRgwF7UCiazNMvW7Md7jVgRcUVfZxMEl5KPpq7ATPV2IaAFbazElAiQn+lBCLGYWA5d/rc8BMptMpimxEG6/mTb7D54bD/lgYfAnlpaD4LgKfBd4fcvAIcwvJYp8e2311wujtmLGFVUpQBq8AWPyN6qbT4HQl07O27B6m6FHH72lwwWCoMA8JtpZc+vuTDmb0Qd8GAD4QCABxnjFHYKuyGc+TvJxKktXR7hweo5SdjHZGAMzaAYKFC503gDLkLUDR1CFXfDqL1Bklg1o7LTiifyT/qZq3yXvZI1KoKOilLlo5DezXrLP0ofALS0Ss2xXXDe0hIK7YE3vMo1ePlAiDMPSQ=
    on_success: change
    on_failure: change
